spring:
  # Setting the name of the APPLICATION.
  application:
    name: BOOKS-DATABASE-LOADER
  data:
    cassandra:
      keyspace-name: main
      username: ${CASSANDRA_DB_USERNAME}
      password: ${CASSANDRA_DB_PASSWORD}
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  main:
    allow-circular-references: true

datastax.astra:
  secure-connect-bundle: secure-connect.zip
# Setting the data dump file location
datadump.location:
  # Change it to your relative location
  authors: /home/denuvo-drm/Downloads/BOOKS_DB/ol_dump_authors_2022-11-30.txt
  works: /home/denuvo-drm/Downloads/BOOKS_DB/ol_dump_works_2022-11-30.txt
astra:
  db:
    id: ${ASTRA_DB_ID}
    region: asia-south1
    keyspace: main
    application.token: ${ASTRA_DB_APPLICATION_TOKEN}